
package wsdemo.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-hudson-53-SNAPSHOT
 * Generated source version: 2.1
 * 
 */
@WebService(name = "\u0414\u0430\u043d\u043d\u044b\u0435\u041d\u043e\u043c\u0435\u043d\u043a\u043b\u0430\u0442\u0443\u0440\u044bPortType", targetNamespace = "http://www.1c.ru/demos/products")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ДанныеНоменклатурыPortType {


    /**
     * 
     * @return
     *     returns wsdemo.client.НоменклатураГруппа
     */
    @WebMethod(operationName = "\u041f\u043e\u043b\u0443\u0447\u0438\u0442\u044c")
    @WebResult(targetNamespace = "http://www.1c.ru/demos/products")
    @RequestWrapper(localName = "\u041f\u043e\u043b\u0443\u0447\u0438\u0442\u044c", targetNamespace = "http://www.1c.ru/demos/products", className = "wsdemo.client.\u041f\u043e\u043b\u0443\u0447\u0438\u0442\u044c")
    @ResponseWrapper(localName = "\u041f\u043e\u043b\u0443\u0447\u0438\u0442\u044cResponse", targetNamespace = "http://www.1c.ru/demos/products", className = "wsdemo.client.\u041f\u043e\u043b\u0443\u0447\u0438\u0442\u044cResponse")
    public НоменклатураГруппа получить();

}
